// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeRxf05DJqmdM5sT3-k7RvPVtwuDzLu9Y',
    appId: '1:1009074100303:web:7f7e5ec396ff32c839b23a',
    messagingSenderId: '1009074100303',
    projectId: 'student-management-12008',
    authDomain: 'student-management-12008.firebaseapp.com',
    storageBucket: 'student-management-12008.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDza50vtN-4Ky9BaUDGFcTM45C3hlAUGac',
    appId: '1:1009074100303:android:74fd22e433bfcd1839b23a',
    messagingSenderId: '1009074100303',
    projectId: 'student-management-12008',
    storageBucket: 'student-management-12008.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1h4ySUifQG9NwXjcgpFuKREyXXNAXrVI',
    appId: '1:1009074100303:ios:80c75d8de5d5895939b23a',
    messagingSenderId: '1009074100303',
    projectId: 'student-management-12008',
    storageBucket: 'student-management-12008.firebasestorage.app',
    iosBundleId: 'com.example.studentManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1h4ySUifQG9NwXjcgpFuKREyXXNAXrVI',
    appId: '1:1009074100303:ios:80c75d8de5d5895939b23a',
    messagingSenderId: '1009074100303',
    projectId: 'student-management-12008',
    storageBucket: 'student-management-12008.firebasestorage.app',
    iosBundleId: 'com.example.studentManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDeRxf05DJqmdM5sT3-k7RvPVtwuDzLu9Y',
    appId: '1:1009074100303:web:c9a199ecd1a0853b39b23a',
    messagingSenderId: '1009074100303',
    projectId: 'student-management-12008',
    authDomain: 'student-management-12008.firebaseapp.com',
    storageBucket: 'student-management-12008.firebasestorage.app',
  );
}
